---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'api/customers/carts/$id/$resource': 'Api\CartController'
    'api/customers/profile/$action': 'Api\ProfileCustomerController'
    'api/customers/$action': 'Api\CustomerController'
    'api/merchants/profile/$action': 'Api\ProfileMerchantController'
    'api/merchants/$action/$field': 'Api\MerchantController'
    'api/products/$id/$resource/$resource_id': 'Api\ProductController'
    'api/orders/$id/$resource/$resource_id': 'Api\OrderController'
    'api/verify/$token': 'Api\VerifyController'
    'api/password_reset/$token': 'Api\ResetPasswordController'
    'api/change_email/$token': 'Api\ChangeEmailController'
    'api/banners': 'Api\BannerController'
    'api/test/$id': 'Api\TestController'
